# Generated by Django 2.2.6 on 2020-06-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_trainer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineractivity',
            name='timing',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
