# Generated by Django 2.2.6 on 2020-06-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_auto_20200611_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alpha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alphabet', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
