# Generated by Django 2.2.6 on 2020-06-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alpha'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.Member')),
                ('trainer_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.TrainerActivity')),
            ],
        ),
        migrations.DeleteModel(
            name='BatchTrainer',
        ),
    ]
